name: Closed PR Notification

on:
  pull_request:
    types:
      - closed # PR이 닫힐 때 실행

jobs:
  close-pull-request:
    name: Discord Notification - Close PR
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Status (merged or closed)
        id: pr_status
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "status=종료된 PR" >> "$GITHUB_OUTPUT"
            echo "color=13202687" >> "$GITHUB_OUTPUT"
          else
            echo "status=반려된 PR" >> "$GITHUB_OUTPUT"
            echo "color=16068656" >> "$GITHUB_OUTPUT"
          fi

      - name: Send Closed PR Notification
        uses: Ilshidur/action-discord@master
        with:
          args: "종료된 PR이 생성되었습니다"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ERINN-HORN-BOT
          DISCORD_AVATAR: "https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true"
          DISCORD_EMBEDS: >
            [{
              "title": "${{ steps.pr_status.outputs.status }} : ${{ github.event.pull_request.title }} (${{ github.event.pull_request.html_url }})",
              "color": ${{ steps.pr_status.outputs.color }},
              "description": "PR NUMBER : #${{ github.event.pull_request.number }}",
              "fields": [
                {
                  "name": "작성자",
                  "value": "${{ github.event.pull_request.user.login }}",
                  "inline": true
                },
                {
                  "name": "작성일",
                  "value": "${{ github.event.pull_request.closed_at }}",
                  "inline": true
                }
              ]
            }]
