name: Closed PR Notification

on:
  pull_request:
    types:
      - closed # PR이 닫힐 때 실행

jobs:
  close-pull-request:
    name: Discord Notification - Close PR
    runs-on: ubuntu-latest
    steps:
      - name: Send Closed PR Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: TIME_LETTER_BOT
          DISCORD_AVATAR: "https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true"
          DISCORD_EMBEDS: '[{"title":"${{ github.event.pull_request.merged == true && ''종료된 PR'' || ''반려된 PR'' }} : ${{ github.event.pull_request.title }}","color":${{ github.event.pull_request.merged == true && 13202687 || 16068656 }},"description":"${{ github.event.pull_request.html_url }}","fields":[{"name":"PR NUMBER","value":"#${{ github.event.pull_request.number }}","inline":true},{"name":"AUTHOR","value":"${{ github.event.pull_request.user.login }}","inline":true}]}]'
