name: Closed Issue Notification

on:
  issues:
    types:
      - closed # 이슈가 닫힐 때 실행

jobs:
  closed-issue:
    name: Discord Notification - Close Issue
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: TIME_LETTER_BOT
          DISCORD_AVATAR: https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true
          DISCORD_EMBEDS: '[{"title":"종료 이슈 사항: ${{ github.event.issue.title }}","color":13202687,"description":"${{ github.event.issue.html_url }}","fields":[{"name":"ISSUE NUMBER","value":"#${{ github.event.issue.number }}","inline":true},{"name":"AUTHOR","value":"${{ github.event.issue.user.login }}","inline":true}]}]'
