name: Opened PR Notification

on:
  pull_request:
    types:
      - opened # PR이 새로 생성될 때 실행

jobs:
  create-pull-request:
    name: Discord Notification - Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Send PR Notification
        uses: Ilshidur/action-discord@master
        with:
          args: "새로운 PR이 생성되었습니다"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GITHUB_BOT
          DISCORD_AVATAR: https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true
          DISCORD_EMBEDS: >
            [{
              "title":"새로운 PR 요청: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})",
              "color":10478271,
              "description":"작성자 : ${{ github.event.pull_request.user.login }}",
              "description":"작성일 : ${{ github.event.pull_request.created_at }}",
              "description":"PR NUMBER : ${{ github.event.pull_request.number }}",
            }]
