name: Opened Issue Notification

on:
  issues:
    types:
      - opened # 이슈가 열릴 때 실행

jobs:
  create-issue:
    name: Discord Notification - Create Issue
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue
        uses: Ilshidur/action-discord@master
        with:
          args: "새로운 이슈가 생성되었습니다"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GITHUB_BOT
          DISCORD_AVATAR: https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true
          DISCORD_EMBEDS: >
            [{
              "title":"신규 이슈 사항:${{ github.event.issue.title }} (${{ github.event.issue.html_url }})",
              "color":10478271,
              "description":"이슈 NUMBER: #${{ github.event.issue.number }}",
              "fields":[
                {
                    "name":"작성자",
                    "value":"${{ github.event.issue.user.login }}",
                    "inline":true
                  },
                  {
                    "name":"작성일",
                    "value":"${{ github.event.issue.created_at }}",
                    "inline":true
                  }
                ]
              }]
