name: Opened Issue Notification

on:
  issues:
    types:
      - opened # 이슈가 열릴 때 실행

jobs:
  create-issue:
    name: Discord Notification - Create Issue
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GITHUB_BOT
          DISCORD_AVATAR: https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true
          DISCORD_EMBEDS: >
            [{
              "title":"신규 이슈 사항:${{ github.event.issue.title }}",
              "color":10478271,
              "description":"${{ github.event.issue.html_url }}",
              "fields":[
                {
                  "name":"ISSUE NUMBER",
                  "value":"#${{ github.event.issue.number }}",
                  "inline":true
                  },
                  {
                    "name":"AUTHOR",
                    "value":"${{ github.event.issue.user.login }}",
                    "inline":true
                  },
                  {
                    "name":"CREATED AT",
                    "value":"${{ github.event.issue.created_at }}",
                    "inline":true
                  }
                ]
              }]
